=== Spratch/legislatures/public/data/schemas/families.json
{
  "$schema": "https://json-schema.org/draft-07/schema",
  "id": "schemas/families.json",
  "type": "array",
  "description": "List of political families",
  "uniqueItems": true,
  "items": {
    "type": "object",
    "description": "A political family",
    "required": ["name", "name_en", "name_de", "color", "currents"],
    "additionalProperties": false,
    "properties": {
      "name": {
        "type": "string",
        "description": "The name of the political family in french"
      },
      "name_en": {
        "type": "string",
        "description": "The name of the political family in english"
      },
      "name_de": {
        "type": "string",
        "description": "The name of the political family in german"
      },
      "color": {
        "type": "string",
        "pattern": "^#([0-9a-fA-F]{6})$",
        "description": "The color associated with this political family, in hex format (#RRGGBB)"
      },

      "currents": {
        "type": "array",
        "description": "List of political currents within this family",
        "uniqueItems": true,
        "items": {
          "type": "object",
          "description": "A political current",
          "required": ["name", "name_en", "name_de", "color", "parties"],
          "additionalProperties": false,
          "properties": {
            "name": {
              "type": "string",
              "description": "The name of the political current in french"
            },
            "name_en": {
              "type": "string",
              "description": "The name of the political current in english"
            },
            "name_de": {
              "type": "string",
              "description": "The name of the political current in german"
            },
            "color": {
              "type": "string",
              "pattern": "^#([0-9a-fA-F]{6})$",
              "description": "The color associated with this political current, in hex format (#RRGGBB)"
            },
            "keyword": {
              "type": "string",
              "description": "The title of the french wikipedia article about this political current"
            },

            "parties": {
              "type": "array",
              "description": "List of parties within this political current",
              "uniqueItems": true,
              "items": {
                "type": "object",
                "description": "A political party",
                "required": [
                  "name",
                  "full_name",
                  "full_name_en",
                  "full_name_de"
                ],
                "additionalProperties": false,
                "properties": {
                  "name": {
                    "type": "string",
                    "description": "The identifier of the political party (usually its acronym), used to link to parties in regimes.json"
                  },
                  "full_name": {
                    "type": "string",
                    "description": "The full name of the political party in french"
                  },
                  "full_name_en": {
                    "type": "string",
                    "description": "The full name of the political party in english"
                  },
                  "full_name_de": {
                    "type": "string",
                    "description": "The full name of the political party in german"
                  },
                  "keyword": {
                    "type": "string",
                    "description": "The title of the french wikipedia article about this party"
                  },
                  "period": {
                    "type": "string",
                    "description": "The period of the political party"
                  }
                }
              }
            }
          }
        }
      }
    }
  }
}

=== Spratch/legislatures/public/data/germany/families.json
[
  {
    "name": "Gauche",
    "name_en": "Left",
    "name_de": "Linke",
    "color": "#FF0E3A",
    "currents": [
      {
        "name": "Communiste",
        "name_en": "Communist",
        "name_de": "Kommunist",
        "color": "#A40C34",
        "keyword": "Communisme",
        "parties": [
          {
            "name": "KPD",
            "full_name": "Parti communiste d'Allemagne",
            "full_name_en": "Communist Party of Germany",
            "full_name_de": "Kommunistische Partei Deutschlands",
            "keyword": "Parti communiste d'Allemagne"
          }
        ]
      },
      {
        "name": "Socialiste démocratique",
        "name_en": "Democratic socialist",
        "name_de": "Demokratischer Sozialist",
        "color": "#C10F3D",
        "keyword": "Socialisme démocratique",
        "parties": [
          {
            "name": "ADAV",
            "full_name": "Association générale des travailleurs allemands",
            "full_name_en": "General Association of German Workers",
            "full_name_de": "Allgemeiner Deutscher Arbeiterverein",
            "keyword": "Association générale des travailleurs allemands",
            "period": "1863-1875"
          },
          {
            "name": "USPD",
            "full_name": "Parti social-démocrate indépendant d'Allemagne",
            "full_name_en": "Independent Social Democratic Party of Germany",
            "full_name_de": "Unabhängige Sozialdemokratische Partei Deutschlands",
            "keyword": "Parti social-démocrate indépendant d'Allemagne",
            "period": "1917-1931"
          },
          {
            "name": "PDS",
            "full_name": "Parti du socialisme démocratique",
            "full_name_en": "Party of Democratic Socialism",
            "full_name_de": "Partei des Demokratischen Sozialismus",
            "keyword": "Parti du socialisme démocratique (Allemagne)"
          },
          {
            "name": "DL.PDS",
            "full_name": "La gauche.PDS",
            "full_name_en": "The left.PDS",
            "full_name_de": "Die Linke.PDS",
            "keyword": "Parti du socialisme démocratique (Allemagne)"
          },
          {
            "name": "DL",
            "full_name": "La gauche",
            "full_name_en": "The left",
            "full_name_de": "Die Linke",
            "keyword": "Die Linke"
          }
        ]
      },
      {
        "name": "Écologiste",
        "name_en": "Ecologist",
        "name_de": "Ökologe",
        "color": "#80C34E",
        "keyword": "Écologie politique",
        "parties": [
          {
            "name": "Gr",
            "full_name": "Les Verts",
            "full_name_en": "The Greens",
            "full_name_de": "Die Grünen",
            "keyword": "Alliance 90/Les Verts"
          }
        ]
      },
      {
        "name": "Social-démocrate",
        "name_en": "Social democrat",
        "name_de": "Sozialdemokrat",
        "color": "#F40E39",
        "keyword": "Social-démocratie",
        "parties": [
          {
            "name": "SDAP",
            "full_name": "Parti ouvrier social-démocrate",
            "full_name_en": "Social Democratic Workers' Party of Germany",
            "full_name_de": "Sozialdemokratische Arbeiterpartei",
            "keyword": "Parti ouvrier social-démocrate (Allemagne)",
            "period": "1869-1875"
          },
          {
            "name": "SAP",
            "full_name": "Parti socialiste ouvrier d'Allemagne",
            "full_name_en": "Socialist Workers' Party of Germany",
            "full_name_de": "Sozialistische Arbeiterpartei Deutschlands",
            "keyword": "Parti socialiste ouvrier d'Allemagne (1875)",
            "period": "1875-1890"
          },
          {
            "name": "SPD",
            "full_name": "Parti social-démocrate d'Allemagne",
            "full_name_en": "Social Democratic Party of Germany",
            "full_name_de": "Sozialdemokratische Partei Deutschlands",
            "keyword": "Parti social-démocrate d'Allemagne"
          }
        ]
      }
    ]
  },
  {
    "name": "Centre",
    "name_en": "Centre",
    "name_de": "Mitte",
    "color": "#FFBC5D",
    "currents": [
      {
        "name": "Social-libéral",
        "name_en": "Social-liberal",
        "name_de": "Sozial-libéral",
        "color": "#FEE098",
        "keyword": "Social-libéralisme",
        "parties": [
          {
            "name": "DtVP",
            "full_name": "Parti populaire allemand",
            "full_name_en": "German People's Party",
            "full_name_de": "Deutsche Volkspartei",
            "keyword": "Parti populaire allemand (Empire allemand)",
            "period": "1868-1910"
          },
          {
            "name": "DDP",
            "full_name": "Parti démocrate allemand",
            "full_name_en": "German Democratic Party",
            "full_name_de": "Deutsche Demokratische Partei",
            "keyword": "Parti démocrate allemand",
            "period": "1918-1930"
          },
          {
            "name": "DStP",
            "full_name": "Parti allemand d'État",
            "full_name_en": "German State Party",
            "full_name_de": "Deutsche Staatspartei",
            "keyword": "Parti démocrate allemand",
            "period": "1930-1933"
          }
        ]
      },
      {
        "name": "Social-libéral protestant",
        "name_en": "Protestant social-liberal",
        "name_de": "Sozialliberaler Protestant",
        "color": "#FEDA80",
        "keyword": "Social-libéralisme",
        "parties": [
          {
            "name": "NSV",
            "full_name": "Association nationale-sociale",
            "full_name_en": "National-Social Association",
            "full_name_de": "Nationalsozialer Verein",
            "keyword": "Association nationale-sociale",
            "period": "1896-1903"
          }
        ]
      },
      {
        "name": "Radical-libéral",
        "name_en": "Radical-liberal",
        "name_de": "Radikale-liberale",
        "color": "#FED264",
        "keyword": "Radical-libéral",
        "parties": [
          {
            "name": "DFP",
            "full_name": "Parti progressiste allemand",
            "full_name_en": "German Progress Party",
            "full_name_de": "Deutsche Fortschrittspartei",
            "keyword": "Parti progressiste allemand",
            "period": "1861-1884"
          },
          {
            "name": "DFP ",
            "full_name": "Parti radical allemand",
            "full_name_en": "German Free-minded Party",
            "full_name_de": "Deutsche Freisinnige Partei",
            "keyword": "Parti radical allemand",
            "period": "1884-1893"
          },
          {
            "name": "FVp",
            "full_name": "Parti populaire radical",
            "full_name_en": "Free-minded People's Party",
            "full_name_de": "Freisinnige Volkspartei",
            "keyword": "Parti populaire radical",
            "period": "1893-1910"
          },
          {
            "name": "FVP",
            "full_name": "Parti populaire progressiste",
            "full_name_en": "Progressive People's Party",
            "full_name_de": "Fortschrittliche Volkspartei",
            "keyword": "Parti populaire progressiste (Empire allemand)",
            "period": "1910-1918"
          }
        ]
      },
      {
        "name": "Minorité danoise",
        "name_en": "Danish minority",
        "name_de": "Dänische Minderheit",
        "color": "#FECD05",
        "keyword": "Danois d'Allemagne",
        "parties": [
          {
            "name": "DP ",
            "full_name": "Parti danois",
            "full_name_en": "Danish Party",
            "full_name_de": "Dänische Partei",
            "keyword": "Danish Party",
            "period": "1871-1919"
          },
          {
            "name": "SSW",
            "full_name": "Fédération des électeurs du Schleswig du Sud",
            "full_name_en": "Federation of Voters of South Schleswig",
            "full_name_de": "Wählerbund Südschleswig",
            "keyword": "Fédération des électeurs du Schleswig du Sud"
          }
        ]
      },
      {
        "name": "Indépendant polonais",
        "name_en": "Polish independent",
        "name_de": "Sonstige Polen",
        "color": "#FFE698",
        "keyword": "Parti polonais",
        "parties": [
          {
            "name": "SP",
            "full_name": "Indépendant polonais",
            "full_name_en": "Polish independent",
            "full_name_de": "Sonstige Polen",
            "keyword": "Parti polonais"
          }
        ]
      },
      {
        "name": "Minorité polonaise",
        "name_en": "Polish minority",
        "name_de": "Polnische Minderheit",
        "color": "#FFDD72",
        "keyword": "Parti polonais",
        "parties": [
          {
            "name": "PF",
            "full_name": "Parti polonais",
            "full_name_en": "Polish Party",
            "full_name_de": "Polnische Fraktion",
            "keyword": "Parti polonais",
            "period": "1848-1903"
          },
          {
            "name": "PNDP",
            "full_name": "Parti national-démocrate polonais",
            "full_name_en": "National Democrat Polish Party",
            "full_name_de": "Polnische Nationaldemokratische Partei",
            "keyword": "Polnische Nationaldemokratische Partei",
            "period": "1903-1924"
          }
        ]
      },
      {
        "name": "Nationaliste polonais",
        "name_en": "Polish Nationalist",
        "name_de": "Polnischer Nationalist",
        "color": "#FED85F",
        "keyword": "Parti polonais",
        "parties": [
          {
            "name": "PNP",
            "full_name": "Parti national polonais",
            "full_name_en": "Polish National Party",
            "full_name_de": "Polnische Nationalpartei",
            "keyword": "Parti polonais",
