=== Spratch/legislatures/public/data/schemas/regimes.json
{
  "$schema": "https://json-schema.org/draft-07/schema",
  "id": "schemas/regimes.json",
  "type": "array",
  "description": "List of regimes",
  "uniqueItems": true,
  "items": {
    "type": "object",
    "description": "A regime",
    "required": ["name", "name_en", "name_de", "begin", "legislatures"],
    "additionalProperties": false,
    "properties": {
      "name": {
        "type": "string",
        "description": "The name of the regime in french"
      },
      "name_en": {
        "type": "string",
        "description": "The name of the regime in english"
      },
      "name_de": {
        "type": "string",
        "description": "The name of the regime in german"
      },
      "begin": {
        "type": "string",
        "format": "date",
        "description": "The start date of the regime"
      },
      "end": {
        "type": ["string", "null"],
        "format": "date",
        "description": "The end date of the regime"
      },

      "legislatures": {
        "type": "array",
        "description": "List of legislatures during this regime",
        "uniqueItems": true,
        "items": {
          "type": "object",
          "description": "A legislature",
          "required": [
            "legislature",
            "total_deputes",
            "begin",
            "end",
            "parties"
          ],
          "additionalProperties": false,
          "properties": {
            "legislature": {
              "type": "number",
              "description": "The year of the legislature, but also its identifier, so it must be unique within the regime (use 1910 and 1910.5 if there are two sessions in the same year)"
            },
            "total_deputes": {
              "type": "number",
              "description": "The total number of deputies in this legislature"
            },
            "duration": {
              "type": "number",
              "description": "The approximate duration of the legislature in years"
            },
            "begin": {
              "type": "string",
              "format": "date",
              "description": "The start date of the legislature"
            },
            "end": {
              "type": "string",
              "oneOf": [
                {
                  "format": "date"
                },
                { "enum": ["now"] }
              ],
              "description": "The end date of the legislature"
            },
            "true-end": {
              "type": ["string", "null"],
              "format": "date",
              "description": "The actual end date of the legislature, for WIP purposes, don't use it in production"
            },
            "comment": {
              "type": ["string", "null"],
              "description": "A comment about the legislature"
            },
            "source": {
              "type": "array",
              "description": "List of sources for this legislature",
              "items": {
                "type": "string",
                "format": "uri"
              }
            },

            "parties": {
              "type": "array",
              "description": "List of parties in this legislature, with their number of deputies. Includes parties that had no deputies but are present in the previous or the next legislature.",
              "uniqueItems": true,
              "items": {
                "type": "object",
                "description": "A party in this legislature",
                "required": ["name", "deputes"],
                "additionalProperties": false,
                "properties": {
                  "name": {
                    "type": "string",
                    "description": "The identifier of the party, must match a party in families.json"
                  },
                  "deputes": {
                    "type": "number",
                    "description": "The number of deputies for this party in this legislature"
                  },
                  "coalition": {
                    "type": ["string", "null"],
                    "description": "The coalition this party is part of, if any"
                  },
                  "coalition_en": {
                    "type": ["string", "null"],
                    "description": "The coalition this party is part of, if any (in english)"
                  },
                  "coalition_de": {
                    "type": ["string", "null"],
                    "description": "The coalition this party is part of, if any (in german)"
                  }
                }
              }
            }
          }
        }
      }
    }
  }
}

=== Spratch/legislatures/public/data/france/regimes.json
[
  {
    "name": "Monarchie constitutionnelle",
    "name_en": "Constitutional monarchy",
    "name_de": "Konstitutionelle Monarchie",
    "begin": "1791-09-03",
    "end": "1792-09-21",
    "legislatures": [
      {
        "legislature": 1791,
        "total_deputes": 745,
        "duration": 1,
        "begin": "1791-10-01",
        "end": "1792-09-21",
        "parties": [
          {
            "name": "MON",
            "deputes": 0
          },
          {
            "name": "GIR",
            "deputes": 136
          },
          {
            "name": "MAR",
            "deputes": 345
          },
          {
            "name": "FEU",
            "deputes": 264
          }
        ]
      }
    ]
  },
  {
    "name": "Première République",
    "name_en": "First Republic",
    "name_de": "Erste Republik",
    "begin": "1792-09-21",
    "end": "1804-05-18",
    "legislatures": [
      {
        "legislature": 1792,
        "total_deputes": 749,
        "duration": 3,
        "begin": "1792-09-21",
        "end": "1795-10-26",
        "parties": [
          {
            "name": "EXG",
            "deputes": 0
          },
          {
            "name": "MON",
            "deputes": 200
          },
          {
            "name": "GIR",
            "deputes": 160
          },
          {
            "name": "MAR",
            "deputes": 389
          },
          {
            "name": "Autres",
            "deputes": 0
          },
          {
            "name": "CLY",
            "deputes": 0
          },
          {
            "name": "ROY",
            "deputes": 0
          }
        ]
      },
      {
        "legislature": 1795,
        "total_deputes": 477,
        "duration": 4,
        "begin": "1795-10-27",
        "end": "1799-04-16",
        "parties": [
          {
            "name": "EXG",
            "deputes": 0
          },
          {
            "name": "MON",
            "deputes": 106
          },
          {
            "name": "GIR",
            "deputes": 0
          },
          {
            "name": "THER",
            "deputes": 135
          },
          {
            "name": "Indé",
            "deputes": 44
          },
          {
            "name": "CLY",
            "deputes": 159
          },
          {
            "name": "ROY",
            "deputes": 33
          }
        ],
        "source": [
          "Puisque la législature de 1795 est renouvelée par tiers en trois élections, j'ai fait le choix d'additionner les résultats des élections de 1795 (150 députés), 1797 (177) et 1798 (150).",
          "https://fr.wikipedia.org/wiki/%C3%89lections_l%C3%A9gislatives_fran%C3%A7aises_de_1795",
          "https://fr.wikipedia.org/wiki/%C3%89lections_l%C3%A9gislatives_fran%C3%A7aises_de_1797",
          "https://fr.wikipedia.org/wiki/%C3%89lections_l%C3%A9gislatives_fran%C3%A7aises_de_1798"
        ]
      },
      {
        "legislature": 1799,
        "total_deputes": 500,
        "duration": 1,
        "begin": "1799-04-16",
        "end": "1799-12-26",
        "parties": [
          {
            "name": "EXG",
            "deputes": 30
          },
          {
            "name": "MON",
            "deputes": 240
          },
          {
            "name": "GIR",
            "deputes": 0
          },
          {
            "name": "MAR",
            "deputes": 0
          },
          {
            "name": "Autres",
            "deputes": 0
          },
          {
            "name": "CLY",
            "deputes": 150
          },
          {
            "name": "BNP",
            "deputes": 0
          },
          {
            "name": "ROY",
            "deputes": 80
          }
        ],
        "source": [
          "https://fr.wikipedia.org/wiki/%C3%89lections_l%C3%A9gislatives_fran%C3%A7aises_de_1799"
        ]
      }
    ]
  },
  {
    "name": "Premier Empire",
    "name_en": "First Empire",
    "name_de": "Erstes Reich",
    "begin": "1804-05-18",
    "end": "1814-04-04",
    "legislatures": [
      {
        "legislature": 1800,
        "total_deputes": 300,
        "duration": 14,
        "begin": "1800-01-01",
        "end": "1814-06-04",
        "parties": [
          {
            "name": "EXG",
            "deputes": 0
          },
          {
            "name": "MON",
            "deputes": 0
          },
          {
            "name": "LIB",
            "deputes": 0
          },
          {
            "name": "CLY",
            "deputes": 0
          },
          {
            "name": "BNP",
            "deputes": 300
          },
          {
            "name": "ROY",
            "deputes": 0
          }
        ],
        "source": [
          "J'aimerai en trouver. Je n'ai aucune donnée sur la législature du premier Empire."
        ]
      }
    ]
  },
  {
    "name": "Première Restauration",
    "name_en": "First Restoration",
    "name_de": "Erste Restaurierung",
    "begin": "1814-04-06",
    "end": "1814-03-20",
    "legislatures": [
      {
        "legislature": 1814,
        "total_deputes": 300,
        "duration": 1,
        "begin": "1814-06-04",
        "end": "1815-03-20",
        "parties": [
          {
            "name": "EXG",
            "deputes": 0
          },
          {
            "name": "MON",
            "deputes": 0
          },
          {
            "name": "LIB",
            "deputes": 0
          },
          {
            "name": "CLY",
            "deputes": 0
          },
          {
            "name": "BNP",
            "deputes": 300
          },
          {
            "name": "ROY",
            "deputes": 0
          }
        ],
        "source": [
          "J'ai seulement trouvé dans la constitution que les députés de cette législature sont restés les mêmes que ceux de la législature précédente.",
          "https://www.conseil-constitutionnel.fr/les-constitutions-dans-l-histoire/charte-constitutionnelle-du-4-juin-1814#articles_transitoires"
        ]
      }
    ]
  },
  {
    "name": "Cent jours",
    "name_en": "Hundred days",
    "name_de": "Herrschaft der Hundert Tage",
    "begin": "1815-03-20",
    "end": "1815-07-08",
    "legislatures": [
      {
        "legislature": 1815,
        "total_deputes": 630,
        "duration": 1,
        "begin": "1815-06-03",
        "end": "1815-07-13",
        "parties": [
          {
            "name": "REP ",
            "deputes": 40
          },
          {
            "name": "LIB",
            "deputes": 510
          },
          {
            "name": "DOC",
            "deputes": 0
          },
          {
            "name": "BNP",
            "deputes": 80
          },
          {
            "name": "UR  ",
            "deputes": 0
          }
        ]
      }
    ]
  },
  {
    "name": "Seconde Restauration",
    "name_en": "Second Restoration",
    "name_de": "Zweite Restaurierung",
    "begin": "1815-07-07",
    "end": "1830-08-02",
    "legislatures": [
      {
        "legislature": 1815,
        "total_deputes": 400,
        "duration": 1,
        "begin": "1815-10-07",
        "end": "1816-09-05",
        "parties": [
          {
            "name": "REP ",
            "deputes": 0
          },
          {
            "name": "LIB",
            "deputes": 0
          },
          {
            "name": "DOC",
            "deputes": 50
          },
          {
            "name": "BNP",
            "deputes": 0
          },
          {
            "name": "UR  ",
            "deputes": 350
          }
        ]
      },
      {
        "legislature": 1816,
        "total_deputes": 258,
        "duration": 4,
        "begin": "1816-11-04",
        "end": "1823-12-24",
        "parties": [
          {
            "name": "REP ",
            "deputes": 20
          },
          {
            "name": "LIB",
            "deputes": 10
          },
          {
            "name": "DOC",
            "deputes": 136
          },
          {
            "name": "UR  ",
            "deputes": 92
          }
        ]
      },
      {
        "legislature": 1824,
        "total_deputes": 430,
        "duration": 3,
        "begin": "1824-03-23",
        "end": "1827-11-05",
        "parties": [
          {
            "name": "REP ",
            "deputes": 0
          },
          {
            "name": "LIB",
            "deputes": 17
          },
          {
            "name": "CD ",
            "deputes": 0
          },
          {
            "name": "UR  ",
            "deputes": 413
          },
          {
            "name": "UCO",
            "deputes": 0
          }
        ]
      },
      {
        "legislature": 1827,
        "total_deputes": 430,
        "duration": 3,
        "begin": "1828-02-05",
        "end": "1830-05-16",
        "parties": [
          {
            "name": "LIB",
            "deputes": 185
          },
          {
            "name": "UR  ",
            "deputes": 170
          },
          {
            "name": "UCO",
            "deputes": 75
          }
        ]
      },
      {
        "legislature": 1830,
        "total_deputes": 556,
        "duration": 1,
        "begin": "1830-06-23",
        "end": "1831-05-31",
        "parties": [
          {
            "name": "LIB",
            "deputes": 274
          },
          {
            "name": "PdR",
            "deputes": 0
          },
          {
            "name": "UR  ",
            "deputes": 282
          },
          {
            "name": "UCO",
            "deputes": 0
          }
        ]
      }
    ]
  },
  {
    "name": "Monarchie de Juillet",
    "name_en": "July Monarchy",
    "name_de": "Juli-Monarchie",
    "begin": "1830-08-09",
    "end": "1848-02-24",
    "legislatures": [
      {
        "legislature": 1831,
        "total_deputes": 459,
        "duration": 3,
        "begin": "1831-07-23",
        "end": "1834-05-25",
        "parties": [
          {
            "name": "PdM",
            "deputes": 73
          },
